routes/web.php
<?php

use Illuminate\Support\Facades\Route;
Auth::routes();
Route::get('/lang/{lang}', [App\Http\Controllers\HomeController::class, 'lang'])->where('lang', 'us|es|cn')->name('lang');
Route::post('/calc', [App\Http\Controllers\CalculatorController::class, 'calc']);
Route::get('/currencies', [App\Http\Controllers\CurrencyController::class, 'index']);
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/startups', [App\Http\Controllers\StartupController::class, 'frontIndex'])->name('startups.index');
Route::get('/startups/{startup}', [App\Http\Controllers\StartupController::class, 'frontShow'])->name('startups.show');
Route::get('/about', [App\Http\Controllers\HomeController::class, 'about'])->name('about');
Route::get('/posts', [App\Http\Controllers\PostController::class, 'frontIndex'])->name('posts.index');
Route::get('/posts/{post}', [App\Http\Controllers\PostController::class, 'frontShow'])->name('posts.show');
Route::post('/posts/{post}/comment', [App\Http\Controllers\PostController::class, 'comment'])->name('posts.comment');
Route::post('/subscribe', [App\Http\Controllers\SubscriberController::class, 'store'])->name('subscribe');
Route::group([
    'prefix'        => '/cabinet',
    'middleware'    => ['auth'],
    'as'            => 'cabinet.'
], function(){
    Route::get('/', [App\Http\Controllers\CabinetController::class, 'index'])->name('index');
    Route::get('/account', [App\Http\Controllers\CabinetController::class, 'account'])->name('account');
    Route::post('/account', [App\Http\Controllers\CabinetController::class, 'accountUpdate'])->name('account.update');
    Route::view('calculator', 'cabinet.calculator')->name('calculator');
    Route::view('course', 'cabinet.cource')->name('course');
    Route::post('/connect', [App\Http\Controllers\CabinetController::class, 'TronAddressUpdate'])->name('tron.update');
});
Route::group([
    'prefix' => '/user',
    'middleware' => ['auth'],
    'as' => 'user.'
], function(){
    Route::get('/profile', [App\Http\Controllers\UserController::class, 'profile'])->name('profile.show');
    Route::post('/profile', [App\Http\Controllers\UserController::class, 'profileUpdate'])->name('profile.update');
});
Route::group([
    'prefix' => '/admin',
    'middleware' => ['auth', 'manager'],
    'as' => 'admin.'
], function(){
    Route::view('/', 'admin.index')->name('index');
    Route::resources([
        'posts' => App\Http\Controllers\PostController::class,
        'startups' => App\Http\Controllers\StartupController::class,
        'slides' => App\Http\Controllers\SlideController::class,
        'subscribers' => App\Http\Controllers\SubscriberController::class,
    ]);
});
Route::group([
    'prefix' => '/admin',
    'middleware' => ['auth', 'admin'],
    'as' => 'admin.'
], function(){
    Route::resources([
        'users' => App\Http\Controllers\UserController::class
    ]);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;
    protected $fillable = [ 'name', 'email', 'password', 'active', 'photo', 'tron_address', 'manager'];

    protected $hidden = [
        'password',
        'remember_token',
    ];
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Storage;
class UserController extends Controller
{
    public function index(){
        $users = User::paginate(50);
        return view('admin.users.index', compact('users'));
    }
    public function edit(User $user){
        return view('admin.users.edit', compact('user'));
    }
    public function profile(){
        $user = auth()->user();
        return view('users.profile', compact('user'));
    }
    public function update(Request $request, User $user){
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|max:255|unique:users,id,' . $user->id,
            'password' => 'nullable|confirmed|string|max:255|min:6'
        ]);
        $data = $request->except('password');
        $data['active'] = $request->has('active');
        $data['manager'] = $request->has('manager');
        if($request->password) $data['password'] = bcrypt($request->password);
        if($request->hasFile('photo')){
            if($user->photo) Storage::delete($user->photo);
            $data['photo'] = $request->file('photo')->store('users');
        }
        $user->update($data);
        session()->flash('success', 'Update successful');
        return back();
    }
    public function destroy(User $user){
        if($user->id == 1) abort(403);
        if($user->photo) Storage::delete($user->photo);
        $user->delete();
        session()->flash('success', 'User deleted');
        return back();
    }
}

resources/views/users/profile.blade.php
@extends('layouts.site')

@section('content')
<h1>{{auth()->user()->name}}</h1>
<form class="form" action="{{route('user.profile.update')}}" method="post" enctype="multipart/form-data">
@csrf
    <div class="row">
        <div class="col-sm-3">
            <div class="text-center">
                @if($user->photo)
                    <img src="/storage/{{$user->photo}}" alt="{{$user->name}}" class="img-fluid">
                @else
                <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="{{auth()->user()->name}}">
                @endif
                <h6>Загрузить новое фото</h6>
                <input type="file" name="photo" class="text-center center-block file-upload">
            </div>
        </div>
        <div class="col-sm-9">  
        
            <div class="form-group">
                <div class="col-xs-6">
                    <label>Имя</label>
                    <input type="text" class="form-control" name="name" value="{{old('name') ? old('name') : $user->name}}">
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-6">
                    <label>E-mail</label>
                    <input type="email" class="form-control" name="email" value="{{old('email') ? old('email') : $user->email}}">
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-6">
                    <label>Пароль</label>
                    <input type="password" class="form-control" name="password">
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-6">
                    <label>Подтвердите пароль</label>
                    <input type="password" class="form-control" name="password_confirmation">
                </div>
            </div>
            <div class="form-group">
                <button class="btn btn-lg btn-success" type="submit">Сохранить</button>
            </div>
        </div>
    </div>
</div>
@stop