routes/web.php
<?php

use Illuminate\Support\Facades\Route;
Auth::routes();
Route::get('/lang/{lang}', [App\Http\Controllers\HomeController::class, 'lang'])->where('lang', 'us|es|cn')->name('lang');
Route::post('/calc', [App\Http\Controllers\CalculatorController::class, 'calc']);
Route::get('/currencies', [App\Http\Controllers\CurrencyController::class, 'index']);
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/startups', [App\Http\Controllers\StartupController::class, 'frontIndex'])->name('startups.index');
Route::get('/startups/{startup}', [App\Http\Controllers\StartupController::class, 'frontShow'])->name('startups.show');
Route::get('/about', [App\Http\Controllers\HomeController::class, 'about'])->name('about');
Route::get('/posts', [App\Http\Controllers\PostController::class, 'frontIndex'])->name('posts.index');
Route::get('/posts/{post}', [App\Http\Controllers\PostController::class, 'frontShow'])->name('posts.show');
Route::post('/posts/{post}/comment', [App\Http\Controllers\PostController::class, 'comment'])->name('posts.comment');
Route::post('/subscribe', [App\Http\Controllers\SubscriberController::class, 'store'])->name('subscribe');
Route::group([
    'prefix'        => '/cabinet',
    'middleware'    => ['auth'],
    'as'            => 'cabinet.'
], function(){
    Route::get('/', [App\Http\Controllers\CabinetController::class, 'index'])->name('index');
    Route::get('/account', [App\Http\Controllers\CabinetController::class, 'account'])->name('account');
    Route::post('/account', [App\Http\Controllers\CabinetController::class, 'accountUpdate'])->name('account.update');
    Route::view('calculator', 'cabinet.calculator')->name('calculator');
    Route::view('course', 'cabinet.cource')->name('course');
    Route::post('/connect', [App\Http\Controllers\CabinetController::class, 'TronAddressUpdate'])->name('tron.update');
});
Route::group([
    'prefix' => '/user',
    'middleware' => ['auth'],
    'as' => 'user.'
], function(){
    Route::get('/profile', [App\Http\Controllers\UserController::class, 'profile'])->name('profile.show');
    Route::post('/profile', [App\Http\Controllers\UserController::class, 'profileUpdate'])->name('profile.update');
});
Route::group([
    'prefix' => '/admin',
    'middleware' => ['auth', 'manager'],
    'as' => 'admin.'
], function(){
    Route::view('/', 'admin.index')->name('index');
    Route::resources([
        'posts' => App\Http\Controllers\PostController::class,
        'startups' => App\Http\Controllers\StartupController::class,
        'slides' => App\Http\Controllers\SlideController::class,
        'subscribers' => App\Http\Controllers\SubscriberController::class,
    ]);
});
Route::group([
    'prefix' => '/admin',
    'middleware' => ['auth', 'admin'],
    'as' => 'admin.'
], function(){
    Route::resources([
        'users' => App\Http\Controllers\UserController::class
    ]);
});

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Fuji Dashboard</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="/vendor/tinymce/tinymce.min.js"></script>
    <script src="/vendor/tinymce/langs/ru.js"></script>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <div class="container-fluid px-0">
            <div class="row no-gutters w-100">
                <div class="col sidebar">
                    <div class="border-right border-left">
                        <div class="media d-flex align-items-center px-3 border-bottom py-1 position-relative">
                            @if(auth()->user()->photo)
                                <img width="53px" src="/storage/{{auth()->user()->photo}}" class="mr-3" alt="{{auth()->user()->name}}">
                            @else
                                <img width="53px" src="/img/nophoto.png" class="mr-3" alt="{{auth()->user()->name}}">
                            @endif
                            <div class="media-body">
                                <p class="font-weight-bolder mb-0">{{auth()->user()->name}}</p>
                                <small class="text-muted text-uppercase">{{auth()->user()->email}}</small>
                            </div>
                            <button class="btn btn-sm btn-outline-secondary sidebar-toggle d-inline-block d-lg-none "><i class="fa fa-close"></i></button>
                        </div>
                        <div class="list-group border-0">
                            @if(0)<a href="{{route('admin.slides.index')}}" class="@if(Route::is('admin.slides.*')) active @endif border-right-0 border-left-0 list-group-item list-group-item-action">Slides</a>@endif
                            <a href="{{route('admin.posts.index')}}" class="@if(Route::is('admin.posts.*')) active @endif border-right-0 border-left-0 list-group-item list-group-item-action">Posts</a>
                            <a href="{{route('admin.startups.index')}}" class="@if(Route::is('admin.startups.*')) active @endif border-right-0 border-left-0 list-group-item list-group-item-action">Startups</a>
                            @if(auth()->user()->admin)
                            <a href="{{route('admin.users.index')}}" class="@if(Route::is('admin.users.*')) active @endif border-right-0 border-left-0 list-group-item list-group-item-action">Users</a>
                            @endif
                            <a href="{{route('admin.subscribers.index')}}" class="@if(Route::is('admin.subscribers.*')) active @endif border-right-0 border-left-0 list-group-item list-group-item-action">Subscribers</a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="border-bottom shadow-sm px-3" style="padding-top:14px;padding-bottom:14px">
                        <div class="d-flex justify-content-between align-items-center w-100">
                            <span class="text-uppercase font-weight-bolder d-none d-md-inline-block">Dashboard</span>
                            <div>
                                <form action="" class="d-inline-block mr-3">
                                    <div class="input-group">
                                        <input type="text" class="form-control form-control-sm" placeholder="Search...">
                                        <div class="input-group-append">
                                            <div class="input-group-text"><i class="fa fa-search"></i></div>
                                        </div>
                                    </div>
                                </form>
                                <button class="btn btn-sm btn-outline-secondary mode">
                                    <i class="fa fa-moon-o"></i>
                                    <i class="fa fa-sun-o"></i>
                                </button>
                                <button class="btn btn-sm btn-outline-secondary"><i class="fa fa-bell"></i></button>
                                <div class="dropdown d-inline-block">
                                    <button data-toggle="dropdown" class="btn btn-sm btn-outline-secondary"><i class="fa fa-cogs"></i></button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a href="{{ route('cabinet.account') }}" class="dropdown-item">Account</a>
                                        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="dropdown-item">Logout</a>
                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                            @csrf
                                        </form>
                                    </div>
                                </div>
                                <button class="btn btn-sm btn-outline-secondary sidebar-toggle d-inline-block d-lg-none "><i class="fa fa-bars"></i></button>
                            </div>
                        </div>
                    </div>
                    <main class="p-3">
                        <div>
                            @if(session()->has('success'))
                            <p class="text-success">{{session()->get('success')}}</p>
                            @elseif(session()->has('error'))
                            <p class="text-error">{{session()->get('error')}}</p>
                            @endif
                            @yield('content')
                        </div>
                    </main>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="FUJI - We love our clients and will be happy to answer all your questions.">
    <meta name="author" content="Ansonika">
    <title>FUJI - We love our clients and will be happy to answer all your questions.</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="/img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="/img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="/img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="/img/apple-touch-icon-144x144-precomposed.png">

    <!-- BASE CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
	<link href="/css/vendors.css" rel="stylesheet">
	<link href="/css/icon_fonts/css/all_icons.min.css" rel="stylesheet">

    <!-- YOUR CUSTOM CSS -->
    <link href="/css/custom.css" rel="stylesheet">
    <style>
        #fake-bg{
            position: fixed;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
            background: rgba(0,0,0,0.6);
        }
        .modal-backdrop{
            display: none;
        }
    </style>
</head>

<body id="login_bg">
<div class="modal fade" id="terms_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Terms and conditions</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam illo quos laborum magni incidunt. Dolor in totam corporis, commodi natus vel omnis sapiente ducimus, repudiandae quibusdam quaerat accusamus architecto ipsa?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="accept_button">Accept</button>
      </div>
    </div>
  </div>
</div>
    <div id="particles-js"></div>
	<nav id="menu" class="fake_menu"></nav>
	
	<div id="preloader">
		<div data-loader="circle-side"></div>
	</div>
	<!-- End Preload -->
	
	<div id="login">
		<aside>
			<figure>
				<a href="{{route('home')}}"><img src="/img/logo.png" width="192" height="42" data-retina="true" alt=""></a>
			</figure>
			@yield('content')
			<div class="copy">© 2021 FUJI new business world</div>
		</aside>
	</div>
	<!-- /login -->
		
	<!-- COMMON SCRIPTS -->
    <script src="/js/jquery-2.2.4.min.js"></script>
    <script src="/js/common_scripts.js"></script>
    <script src="/js/main.js"></script>
	<script src="/assets/validate.js"></script>	
    <script src="https://cdnjs.cloudflare.com/ajax/libs/particles.js/2.0.0/particles.min.js"></script>
    <script>
        window.onload = function(){
            particlesJS("particles-js", {
            "particles": {
                "number": {
                "value": 100,
                "density": {
                    "enable": true,
                    "value_area": 800
                }
                },
                "color": {
                    "value": "#ffffff"
                },
                "shape": {
                    "type": "circle",
                    "stroke": {
                        "width": 0,
                        "color": "#000000"
                    },
                    "polygon": {
                        "nb_sides": 5
                    },
                    "image": {
                        "src": "img/github.svg",
                        "width": 100,
                        "height": 100
                    }
                },
                "opacity": {
                "value": 0.5,
                "random": false,
                "anim": {
                    "enable": false,
                    "speed": 1,
                    "opacity_min": 0.1,
                    "sync": false
                }
                },
                "size": {
                "value": 3,
                "random": true,
                "anim": {
                    "enable": false,
                    "speed": 40,
                    "size_min": 0.1,
                    "sync": false
                }
                },
                "line_linked": {
                "enable": true,
                "distance": 150,
                "color": "#ffffff",
                "opacity": 0.4,
                "width": 1
                },
                "move": {
                "enable": true,
                "speed": 6,
                "direction": "none",
                "random": false,
                "straight": false,
                "out_mode": "out",
                "bounce": false,
                "attract": {
                    "enable": false,
                    "rotateX": 600,
                    "rotateY": 1200
                }
                }
            },
            "interactivity": {
                "detect_on": "canvas",
                "events": {
                "onhover": {
                    "enable": true,
                    "mode": "grab"
                },
                "onclick": {
                    "enable": true,
                    "mode": "push"
                },
                "resize": true
                },
                "modes": {
                "grab": {
                    "distance": 140,
                    "line_linked": {
                    "opacity": 1
                    }
                },
                "bubble": {
                    "distance": 400,
                    "size": 40,
                    "duration": 2,
                    "opacity": 8,
                    "speed": 3
                },
                "repulse": {
                    "distance": 200,
                    "duration": 0.4
                },
                "push": {
                    "particles_nb": 4
                },
                "remove": {
                    "particles_nb": 2
                }
                }
            },
            "retina_detect": true
            });

        };
    </script>
</body>
</html>

resources/views/layouts/site.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{{__('ui.title')}}">
    <meta name="author" content="Ansonika">
    <title>{{__('ui.title')}}</title>

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Styles -->
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
    <!-- BASE CSS -->
    <link href="/css/app.css" rel="stylesheet">
	<script src="{{ asset('js/app.js') }}" defer></script>
</head>
<body id="front">
	<div>
		<header>
			<nav class="navbar navbar-expand-lg navbar-dark pb-0">
				<div class="container">
					<a class="navbar-brand" href="{{route('home')}}"><img src="/img/logo.png" alt=""></a>
					<div>
						<a class="mode mr-2 d-inline-block d-md-none" href="#">
							<img src="/img/icons/sun.svg" class="sun">
							<img src="/img/icons/moon.svg" class="moon">
						</a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
					</div>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav ml-auto d-flex align-items-center">
							@auth
							<li class="nav-item"><a class="nav-link pt-1" href="{{route('cabinet.index')}}"><img src="/img/icons/user.svg" alt=""></a></li>
							@else
							<li class="nav-item"><a class="nav-link pt-1" href="{{route('login')}}"><img src="/img/icons/user.svg" alt=""></a></li>
							@endauth
							<li class="nav-item @if(Route::is('home')) active @endif"><a class="nav-link" href="{{route('home')}}">{{__('ui.links.home')}}</a></li>
							<li class="nav-item @if(Route::is('about')) active @endif"><a class="nav-link" href="{{route('about')}}">{{__('ui.links.about')}}</a></li>
							<li class="nav-item @if(Route::is('posts.*')) active @endif"><a class="nav-link" href="{{route('posts.index')}}">{{__('ui.links.blog')}}</a></li>
							<li class="nav-item d-none d-md-block">
								<a class="nav-link mode pt-1" href="#">
									<img src="/img/icons/sun.svg" class="sun">
									<img src="/img/icons/moon.svg" class="moon">
								</a>
							</li>
							<li class="nav-item dropdown">
								<a class="nav-link d-flex justify-content-center align-items-center" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<img src="/flags/4x3/{{$lang}}.svg" width="24px">
									<i class="fa fa-chevron-down ml-2"></i>
								</a>
								<div class="dropdown-menu py-0" aria-labelledby="navbarDropdown">
									@foreach($langs as $key => $item)
										<a class="dropdown-item" href="{{route('lang', $key)}}"><img src="/flags/4x3/{{$key}}.svg" width="24px"> {{$item}}</a>
									@endforeach
								</div>
							</li>
						</ul>
					</div>
				</div>
			</nav>
			@if(Route::is('home'))
			<div class="container pb-3 pb-md-0 position-relative">
				<div class="img"></div>
				<div class="jumbotron px-0">
					<h1>{{__('ui.banner.title')}}</h1>
					<p style="width: 100%; max-width: 500px;">{{__('ui.banner.text')}}</p>
					<a href="{{route('cabinet.index')}}" class="btn rounded-pill btn-primary px-5">{{__('ui.banner.button')}}</a>
				</div>
				@if(env('APP_ENV') != 'local')
				<div class="tradingview-widget-container my-5">
					<div class="tradingview-widget-container__widget"></div>
					<script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js" async>
					{
					"symbols": [
						{
						"proName": "FOREXCOM:SPXUSD",
						"title": "S&P 500"
						},
						{
						"proName": "FOREXCOM:NSXUSD",
						"title": "NASDAQ 100"
						},
						{
						"proName": "FX_IDC:EURUSD",
						"title": "EUR/USD"
						},
						{
						"proName": "BITSTAMP:BTCUSD",
						"title": "BTC/USD"
						},
						{
						"proName": "BITSTAMP:ETHUSD",
						"title": "ETH/USD"
						}
					],
					"showSymbolLogo": true,
					"colorTheme": "dark",
					"isTransparent": false,
					"displayMode": "adaptive",
					"locale": "ru"
					}
					</script>
				</div>
				@endif
				<div class="row">
					<div class="col-4 text-primary text-center d-md-flex d-block align-items-center justify-content-start mb-3 mb-md-0">
						<img src="/img/menu2.png" class="d-inline-block mr-md-3 mr-0 mb-3 mb-md-0" width="48px">
						<div>{{__('ui.banner.link1')}}</div>
					</div>
					<div class="col-4 text-primary text-center d-md-flex d-block align-items-center justify-content-start mb-3 mb-md-0">
						<img src="/img/menu3.png" class="d-inline-block mr-md-3 mr-0 mb-3 mb-md-0" width="48px">
						<div>{{__('ui.banner.link2')}}</div>
					</div>
					<div class="col-4 text-primary text-center d-md-flex d-block align-items-center justify-content-start mb-3 mb-md-0">
						<img src="/img/menu1.png" class="d-inline-block mr-md-3 mr-0 mb-3 mb-md-0" width="48px">
						<div>{{__('ui.banner.link3')}}</div>
					</div>
				</div>
			</div>
			@endif
		</header>
		<main class="d-block pb-5" id="app">
			<div class="container py-3">
				<div class="bread d-flex align-items-center">
					@yield('bread')
				</div>
			</div>
			@yield('content')
		</main>
	</div>
	<footer>
		<div class="container py-5">
			<div class="row">
				<div class="col-md-3">
					<p><img src="/img/logo.png" width="192" height="42" data-retina="true" alt=""></p>
					<p>{{__('ui.footer.desc')}}</p>
				</div>
				<div class="col-md-9">
					<div class="row">
						<div class="col-md-6">
							<p class="font-weight-bolder">{{__('ui.footer.links')}}</p>
							<a href="{{route('posts.index')}}" class="text-white d-block">{{__('ui.links.blog')}}</a>
							<a href="{{route('login')}}" class="text-white d-block">{{__('ui.links.login')}}</a>
							<a href="{{route('register')}}" class="text-white d-block">{{__('ui.links.register')}}</a>
							<a href="/files/offer.pdf" target="_blank" class="text-white d-block">{{__('ui.links.offer')}}</a>
						</div>
						<div class="col-md-6">
							<p class="font-weight-bolder">{{__('ui.footer.contacts')}}</p>
							<a href="mailto:support@fujicompany.io" class="d-block text-white mb-2">support@fujicompany.io</a>
							<a href="https://twitter.com/fjtfuji?s=21" class="mx-2"><img src="/img/icons/tw.svg" alt=""></a>
							<a href="https://t.me/fuji_company" class="mx-2"><img src="/img/icons/tg.svg" alt=""></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	@if(session()->has('success') || session()->has('error'))
    <div class="modal visible">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{__('ui.notifications')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @if(session()->has('success'))
                    <div class="alert alert-success">{{__('ui.' . session('success'))}}</div>
                    @elseif(session()->has('error'))
                    <div class="alert alert-danger">{{__('ui.' . session('error'))}}</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    @endif
</body>
</html>